// Generated by CoffeeScript 1.3.3
(function() {
  var md;

  md = require("../lib/markdown-word");

  md.documentFromFile(__dirname + "/example.md", __dirname + "/example.docx", (function(err, data) {
    return console.log(err, JSON.stringify(data, null, 2));
  }), 0);

}).call(this);
